version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - "discovery.type=single-node"
      volumes:
        - "${PWD}/esdata:/usr/share/elasticsearch/data"
      networks:
        - es
    kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:6.5.3
      ports:
        - "5601:5601"
      volumes:
        - "${PWD}/kibana.yml:/usr/share/kibana/config/kibana.yml"
      networks:
        - es
      depends_on:
        - elasticsearch

networks:
  es:
    driver: bridge
